### ISSUE TITLE
Unicode et UTF-8

### ISSUE THREAD

**Issue by bortzmeyer** [YannisDelmas/beau-code-web#16]
>  À défaut d’UTF-8, l’encodage devrait être, au moins, en Unicode. 

Comme UTF-8 est un encodage d'Unicode, cela n'a guère de sens. Plutôt écrire «  À défaut d’UTF-8, l’encodage devrait être, au moins, dans un encodage d'Unicode. »

**Comment by YannisDelmas** [comment]
Salut Stéphane. Très heureux de te voir ici. Merci pour la rectification. C'est noté.

**Comment by YannisDelmas** [comment]
Références:

- https://encoding.spec.whatwg.org/
- "Text is said to be in a Unicode encoding form if it is encoded in UTF-8, UTF-16 or UTF-32." <https://www.w3.org/TR/charmod/#sec-Digital>
- «The IETF Charset Policy [RFC 2277] specifies that on the Internet "Protocols MUST be able to use the UTF-8 charset".» <https://www.w3.org/TR/charmod/#C018>
- "The XML 1.0 specification [XML 1.0] requires all conforming XML processors to accept both UTF-16 and UTF-8." <https://www.w3.org/TR/charmod/#C018> <https://www.w3.org/TR/2006/REC-xml11-20060816/>
- "A character encoding, or just encoding where that is not ambiguous, is a defined way to convert between byte streams and Unicode strings, as defined in Encoding." <https://html.spec.whatwg.org/multipage/infrastructure.html#encoding-terminology>
