### ISSUE TITLE
CSS: Ordre des déclarations dans une règle

### ISSUE THREAD

**Issue by YannisDelmas** [YannisDelmas/beau-code-web#21]
Quelques éléments pour organiser de façon lisible les déclarations au sein d'une règle. Cf. les _guidelines_ d' @enguerranws: <https://github.com/enguerranws/ew-guidelines#ordre-des-d%C3%A9clarations>.

1. Si une propriété ② dont le sens dépend d'une propriété ① pour son interprétation, il est impératif qu'elle apparaisse après celle-ci.
  - Exemple: `left`, `top`… dépendent de `position`, `vertical-align` dépend de `display`, les dimensions dépendent de `box-sizing`.
  - Justification: sans cette règle pour une compréhension correcte de la règle CSS, un lecteur doit soit faire des aller-retours parmi les déclarations, soit conserver en mémoire de travail l'ensemble de la règle avant de pouvoir l'interpréter, dans les deux cas, la systématisation de cette règle d'ordre permet une réduction de la charge mentale et une limitation des erreurs d'interprétation.
2. Grouper les propriétés par blocs cohérents (cf. <https://www.alsacreations.com/actu/lire/497-de-lordre-que-diable-.html>): nature de l'élément (display), contenu (content, compteurs), mise en page (layout) (visibilité, position, top, right, bottom, left, z-index, float, clear), boîte (margin-*, padding-*, border-*, dimensions), mise en forme (typographie (police et autre propriétés de texte), couleurs, images dont marqueurs, bordures et arrière-plan). Pour plus de lisibilité certains blocs ou sous-blocs peuvent être séparés par des lignes vides.
  - Les blocs peuvent être délimités plus finement pour suivre une logique "outside-in" (cf. <https://dev.to/thekashey/happy-potter-and-the-order-of-css-5ec#groups>)
  - Au sein d'un bloc, la règle 1 s'applique.
  - Dans certains cas, il faut ordonner les blocs d'après la règle 1, par exemple si des dimensions sont exprimées en `em`, il faut placer le bloc de mise en forme avant les précédents. Autre exemple: le sens de tous les autres blocs dépend de la nature et du contenu d'un élément, les blocs de nature et de contenu doivent donc être placés en premier.
  - Plus: Cas particulier de la propriété `display`. Il désigne normalement la nature, donc doit apparaître en premier. Il est parfois utilisé pour gérer la visibilité avec les valeurs `none` ou `contents` et relève alors du bloc de mise en page. De ce fait, il est recommandé d'éviter les bascules `display: block;`/`display:none;`. (Expliquer comment éviter ça simplement)
  - Justification: charge mentale: règle de proximité. Modularité (separation of concerns). Plus: <https://dev.to/thekashey/happy-potter-and-the-order-of-css-5ec#reasons-to-use-groups>
3. `!important` ne devrait jamais avoir à apparaître (#22), mais s'il n'y a _vraiment_ **vraiment** pas le choix, il faut mettres les déclarations correspondantes en premier ou en dernier. Justification: casse la règle de cascade.

Contre-argument contre les groupes: c'est plus facile de se repérer avec l'ordre alphabétique (ABCSS), recommandé par certaines _guidelines_. C'est probablement un effet d'habitude: la plupart du temps, la "raison" invoquée est l'expérience.

**Comment by enguerranws** [comment]
Concernant l'ordre alphabétique des déclarations, il y a pas mal de choses qui peuvent poser souci selon moi (notamment si on doit ranger alphabétiquement les propriétés préfixés `-webkit-appearance`...).

> Contre-argument contre les groupes: c'est plus facile de se repérer avec l'ordre alphabétique (ABCSS), recommandé par certaines guidelines. C'est probablement un effet d'habitude: la plupart du temps, la "raison" invoquée est l'expérience.

Il s'agit de quelles guidelines ?

**Comment by YannisDelmas** [comment]
C'est le cas des [Google HTML/CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.html): [§ 4.2.1 Declaration Order](https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order). Ils prennent la précaution quand même de "Ignore vendor-specific prefixes for sorting purposes". Leur argument: "in order to achieve consistent code in a way that is easy to remember and maintain".

**Comment by YannisDelmas** [comment]
Branche [proposition/css-ordre-declarations](https://github.com/YannisDelmas/beau-code-web/tree/proposition/css-ordre-declarations) créée pour cette issue.

**Comment by YannisDelmas** [comment]
@enguerranws Quand tu auras un instant, je veux bien que tu jettes un œil à mon premier jet pour cette règle.

**Comment by enguerranws** [comment]
@YannisDelmas Ce qu'il y a me paraît déjà bien et complet. Le reste des choses qu'on pourrait ajouter me semble subjectif.
