### ISSUE TITLE
HTML : les images déclarent systématiquement un attribut alt, qui doit reporter l'information donnée par l'image. C'est généralement le texte qu'elle contient. Pour proposer une description à l'image, on préférera l'attribut title.

### ISSUE THREAD

**Issue by enguerranws** [YannisDelmas/beau-code-web#5]
J'ai commencé, et j'ai l'impression que les choses ont pas mal bougées de ce côté là.

Par exemple, l'arbre de décision pour remplir l'élément alt d'une image, par le W3C : https://www.w3.org/WAI/tutorials/images/decision-tree/

**Comment by enguerranws** [comment]
J'avais commencé cette section par : 
```
 Les attributs alt des éléments HTML img () doivent respecter les règles suivantes.

    La présence de cet attribut alt est obligatoire, même vide.

    Le contenu de cet attribut alt ne doit pas servir uniquement à placer des mots-clé dans le but d'atteindre de meilleures performances en terme de référencement (SEO).

    La contenu de cet attribut alt devrait servir à reporter le texte contenu dans l'image..

    La contenu de cet attribut alt ne devrait pas servir de description à l'image.

    La contenu de cet attribut alt peut contenir des mots-clé utiles au bon référencement de l'image et de la page consultée en général.
```

Mais ça ne me semble pas correspondre aux standards du W3C sur ce point (pour eux, il y a quasiment une solution par cas de figure).

**Comment by YannisDelmas** [comment]
Je ne suis pas sûr qu'on puisse tout décrire tous les cas. Pour ma part, j'aurais insisté sur la notion de _texte alternatif_, en remplacement de ton 3e point. En précisant, par exemple, qu'une image purement décorative impose donc un `alt` vide.
Pour aller plus loin j'aurais bien renvoyé vers des pages web qui expliquent bien comment rédiger le `alt`. Tes quatre autres points me conviennent bien.

Dans les "+", j'ajouterais bien un renvoi vers OpQuast : 4, 1, 73 et 3 en relativisant, 24, 5 en relativisant.

**Comment by YannisDelmas** [comment]
Pour info, j'ajoute les références OpQuast:

- [[Opquast, règle 111](https://checklists.opquast.com/fr/assurance-qualite-web/chaque-image-decorative-est-dotee-dune-alternative-textuelle-appropriee)] Chaque image décorative est dotée d'une alternative textuelle appropriée.
- [[Opquast, règle 112](https://checklists.opquast.com/fr/assurance-qualite-web/chaque-image-lien-est-dotee-dune-alternative-textuelle-appropriee)] Chaque image-lien est dotée d'une alternative textuelle appropriée.
- [[Opquast, règle 113](https://checklists.opquast.com/fr/assurance-qualite-web/chaque-image-porteuse-dinformation-est-dotee-dune-alternative-textuelle-appropriee)] Chaque image porteuse d'information est dotée d'une alternative textuelle appropriée.

**Comment by YannisDelmas** [comment]
@enguerranws J'ai fait la plupart des corrections de chefs-d'œuvre des M2 Web éditorial pour cette année et beaucoup ne sont pas au clair sur cette question. En particulier, dans leurs checklists (pour moi et pour leur recette interne), ils ne font pas toujours bien la distinction entre «image décorative», «image-lien» et «image porteuse d'information». Est-ce que tu es OK pour que je fasse un premier jet de recommandation sur la base de ta proposition et de mes commentaires ci-dessus?

Je mettrais bien des images d'exemples tirées de [Lorem picsum](https://picsum.photos) et, pour le logo, un exemple tiré du [Générateur de logo de mairie](https://geoffreydorne.com/mairie/) de Geoffrey Dorne (pour le clin d'œil).

**Comment by YannisDelmas** [comment]
Exemples de commentaires faits en retour à des projets d'étudiants: intérêt pour le SEO, éviter la description (p.ex. «hopital» et non «photographie d’hopital»), penser fonctionnel (p.ex. «chercher» et non «loupe»).

**Comment by enguerranws** [comment]
@YannisDelmas ça me semble assez complet comme ça, et plus digeste que l'arbre de décision du W3C. Mais je me demande, on le rajouterai pas en référence quand même ?

**Comment by YannisDelmas** [comment]
@enguerranws Ça pourrait donner ça. J'ai ajouté l'exemple des fonctions et un lien vers l'arbre de décision du W3C. Si cette rédaction te convient, il resterait à ajouter les justifications.

J'ai fait un premier style de tableaux. N'hésite pas à améliorer le look 😉
