### ISSUE TITLE
CSS : organiser ses déclarations au sein d'une règle

### ISSUE THREAD

**Issue by YannisDelmas** [YannisDelmas/beau-code-web#6]
Il faudrait qu'on discute de ça.

@enguerranws , à propos du thème `mint-and-grapes.css` indique qu'il préfère mettre les déclarations sur une seule ligne. Pour ma part, je trouve plus lisible de mettre des déclarations qui vont ensemble sur une même ligne, quand elle n'est pas trop longue.

De la même façon, dans une liste de sélecteur, OK pour un par ligne en général, mais quand c'est des choses courtes qui vont ensemble, je trouve que c'est plus lisible sur une ligne. Exemple: une règle qui concerne tous les titres.

**Comment by enguerranws** [comment]
c'est ça @ssorin.

`left: -1.5em;  width: 1em;`

**Comment by ssorin** [comment]
dak, dans ce cas là, je préfère également une déclaration par ligne, je trouve ça beaucoup plus lisible à l'usage

**Comment by enguerranws** [comment]
C'est ouvert à discussion. 

Personnellement : 
- une déclaration par ligne, je trouve ça plus lisible (c'est subjectif)
- ça permet de commenter / supprimer plus vite
- selon les personnes, j'ai pu constater que le regroupement "logique" de déclarations est très variable d'un individu à l'autre (certains vont mettre z-index avec transform et position, parce qu'ils relèvent du changement de stacking context, et d'autres non)

Quelques ressources, au cas où : 
- R. Goetter va dans le sens d'une déclaration par ligne (je crois, mais je ne retrouve pas la ressource), mais propose également de les classer, ce que je n'ai jamais fait personnellement :) https://raphaelgoetter.wordpress.com/2011/12/20/ordonnez-vos-declarations-css/
- un argument intéressant : un changement = une ligne, ce qui est proposé par cet article https://css-tricks.com/single-line-vrs-multi-line-css/. Ça impose que si une règle ne comporte qu'une déclaration, elle se retrouve sur une ligne (je suis pas fan de ce point, parce qu'en cas d'ajout une déclaration, il faut reformater la règle).

**Comment by YannisDelmas** [comment]
Personnellement, voici la règle que j'ai l'habitude d'appliquer.

- Si deux déclarations ou plus fonctionnent ensemble, alors on les met sur la même ligne (en ne dépassant pas 80 car.):
  ```
  .exemple {
      position: absolute; left: 0; right: 0; top: 40px;
      …
  }
  ```
- S'il n'y a qu'une ligne de déclaration(s) et une ligne de sélecteur(s), on met tout sur la même ligne.

Si on doit recommander telle approche ou telle autre, il me semble qu'il faudrait trouver des arguments rationnels. J'ai peur que la lisibilité ne soit pas facile à jauger sans pouvoir réellement expérimenter sur des cobayes: trop subjectif. Mon idée du groupement des choses qui fonctionnent ensemble est de faire comme-si on avait une [propriété raccourcie](https://developer.mozilla.org/fr/docs/Web/CSS/Shorthand_properties), comme `border` ou `flex`. Ces groupes de déclarations fonctionneraient comme un seul ordre. Je vois trop de règles de style où l'on ne dégage pas l'idée directrice. En revanche, je ne généraliserait peut-être pas le fait d'utiliser des propriétés raccourcies: comme le font remarquer [les guildelines du MDN](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/CSS), certaines déclarations deviennent alors trop illisibles (parce que réservées aux personnes très savantes en CSS), p.ex. `font`.

La proposition d'ordonancement de Goetter n'est pas inintéressante, mais, franchement, je ne suis pas sûr d'en voir la raison. Personnellement, je préfère faire des sections différentes dans la feuille de style, avec des vrais titres en commentaire, qu'on peut repérer d'un coup d'œil sur la minimap. Autre idée que je rejette totalement, la [proposition de Google](https://google.github.io/styleguide/htmlcssguide.html) d'ordonner par ordre alphabétique (la plupart des autres recommandation me plaisent bien).

En parlant de Goetter, je suis tombé sur ce vieil article, dont certains éléments me semblent intéressant: <https://www.alsacreations.com/article/lire/1707-Mini-Convention-CSS.html>

À force de chercher, j'ai fini par tomber sur [un argument vraiment rationel](https://cssguidelin.es/#multi-line-css), en faveur du multiligne:

> A reduced chance of merge conflicts, because each piece of functionality exists on its own line.
> More ‘truthful’ and reliable diffs, because one line only ever carries one change.

À noter, toutefois, que l'auteur admet des exceptions.

**Comment by enguerranws** [comment]
> À force de chercher, j'ai fini par tomber sur un argument vraiment rationel, en faveur du multiligne:
> 
>     A reduced chance of merge conflicts, because each piece of functionality exists on its own line.
>     More ‘truthful’ and reliable diffs, because one line only ever carries one change.

Je ne retrouvais plus cette page, mais j'allais dans ce sens aussi. D'ailleurs, de mon point de vue, il y a pas mal de choses qui peuvent être reprises de CSS Guidelines.

Pour moi, si je récapitule les avantages objectifs du CSS multiligne : 
- une logique : un changement, une "fonctionnalité" = une ligne
- ça réduit les chances de conflits lors des merge
- commenter / supprimer plus vite (si on prend l'exemple de position, accolé avec top, left, bottom, si je ne veux commenter que left, c'est plus compliqué)
- c'est une règle qu'il est facile de faire appliquer et respecter : le regroupement par type de règle, chacun va trouver une logique pour faire ses regroupements, ça me parait donc assez subjectif.

**Comment by YannisDelmas** [comment]
OK pour moi. Partons là-dessus.

**Comment by enguerranws** [comment]
Est-ce que tu pourras la rédiger @YannisDelmas ? J'ai peur de m'y perdre dans la rédaction en mode RFC2119 de ce qu'on vient de se dire...

**Comment by YannisDelmas** [comment]
Si tu veux, mais, il ne faut pas que cette histoire de RFC2119 te chagrine. On peut commencer sans et puis compléter, discuter, etc.

**Comment by enguerranws** [comment]
Du tout, je pense que c'est une bonne chose, c'est juste que je n'y suis pas habitué :)
Sur ce point en particulier, j'ai peur de me mélanger les pinceaux et d'y passer beaucoup (trop) de temps :)

**Comment by YannisDelmas** [comment]
J'ai fait un premier jet, avec le RFC2119. Je n'ai pas mis les justifications, pour l'instant.

**Comment by enguerranws** [comment]
Je me disais, pour compléter sur les styles, dans la mesure où on précise que `Chaque déclaration doit se terminer par un point-virgule ;`, on pourrait compléter avec quelques règles qui _devraient_ être appliquée : 
- l'indentation utilisée doit être constante (à voir si ce n'est pas à mettre dans les recommandations générales ?) 
- la propriété devrait être suivi directement de `:`, pas d'espace intercalaire
- l'ouverture des accolades, à la suite de sélecteur devrait être suivi d'une espace (un ou une ? c'est une espace typographique dans ce contexte ?)
- la valeur d'une déclaration devrait être précédée d'un•e espace
- dans le cas d'un groupe de sélecteur, chaque sélecteur devrait être sur une ligne (retour à la ligne après la virgule)

Là, il s'agit d'un parti pris, la vraie recommandation est de garder les espacements / retours à la ligne de façon constante et cohérente sur un projet, pour éviter ce genre là : 

```
.selecteur-1{
  color:white;
  display :block;
  background : red;
}
.selecteur-2 {
color: red;
  display:inline;
}
```

**Comment by YannisDelmas** [comment]
Pour l'indentation, j'en ferais bien un point spécifique, au moins le temps d'en discuter. Certains indentent des règles qui dépendent d'une règle précédente.

Un ou une espace, bonne question… J'y réfléchirai: est-on vraiment dans le champ typo? J'ai des arguments dans les deux sens, pour l'instant.

J'ajoute les autres points.

**Comment by YannisDelmas** [comment]
Bon, zut, je m'aperçois que j'ai `commit` ma proposition sur le CSS directement dans `dev` au lieu de la branche que j'avais créée pour ! Je vais essayer de rectifier ça… 🙄

**Comment by YannisDelmas** [comment]
@ssorin @enguerranws Pourriez-vous regarder le 1er jet dans la branche [proposition/css-ecriture-regles](https://github.com/YannisDelmas/beau-code-web/tree/proposition/css-ecriture-regles) ? Si ça vous convient, je rédige les justifications.

**Comment by enguerranws** [comment]
@YannisDelmas Je viens de regarder, ça me parait bien. Ça m'a fait penser à un point plus global : [la dernière ligne d'un fichier](https://github.com/YannisDelmas/beau-code-web/issues/17)

**Comment by YannisDelmas** [comment]
Je me suis dit que ça serait bien de faire un petit résumé visuel. @ssorin @enguerranws @rachelwe n'hésitez pas à me dire ce que vous en pensez. J'ai peur que ce soit un peu chargé.

En faisant ça, je me suis rendu compte qu'il serait bien de cadrer aussi l'espacement autour des virgules. J'ai ajouté ça à la règle. C'est OK pour vous?

**Comment by enguerranws** [comment]
@YannisDelmas Complètement, ça casse juste chez moi, sur Firefox / MacOs. Mais je peux regarder quand j'ai un moment.
<img width="924" alt="Capture d’écran 2022-01-26 à 11 28 43" src="https://user-images.githubusercontent.com/2190121/151147107-5d7ffaa2-8518-4755-9765-0f599d0ac89b.png">

De mémoire, tu avais fait un outil de parsing / lecture de règles CSS : c'est un super outil je trouve, ça vaudrait peut être le coup de placer un lien (si accessible publiquement) ?

**Comment by enguerranws** [comment]
J'ai poussé une correction pour régler le souci d'affichage mentionné précédemment.

**Comment by YannisDelmas** [comment]
Bien vu! J'ai ajouté un lien vers mon explicateur de CSS et un vers _Can I use…_ Ça me semble bien, maintenant. Je vais faire une proposition de fusion.

**Comment by enguerranws** [comment]
On pourra plus tard mettre (en vrac, sans ordre de priorité) : 
- une recommandation pour grouper les déclarations selon leur "appartenance" (ex : position avec top/left/right/bottom, etc)
- le fait d'indenter des sélecteurs enfants par rapport à leur parent
- la mise en place d'un reset CSS
- l'utilisation de fallbacks pour les propriétés ou valeurs pas encore complètement supportées (soit manuellement, soit via un préprocesseur / postprocesseur)
- peut être, même si ça parait délicat : le fait de ne pas avoir de règles CSS qui ne sont pas en rapport avec le DOM courant. Ça fait référence aux techniques de tree-shaking etc, pour éviter d'avoir des tonnes de CSS pour un site one-page.

Je vais créer des tickets en rapport pour en discuter ou fermer si ce n'est pas pertinent.
