### ISSUE TITLE
HTML : valide

### ISSUE THREAD

**Issue by YannisDelmas** [YannisDelmas/beau-code-web#7]
le code produit est valide

**Comment by YannisDelmas** [comment]
Voici ce que je compte mettre:

- Le balisage DOIT être valide → respect des std ("Using valid HTML is a measurable baseline quality attribute that contributes to learning about technical requirements and constraints, and that ensures proper HTML usage."), sécurité (interprétation univoque) ; outils: navigateur, [valideur W3C](https://validator.w3.org/), vérificateur de l'éditeur de code. Notamment: 
  - Les éléments DOIVENT être correctement imbriqués.
  - Les caractères spéciaux et DOIVENT toujours être correctement échappés par des entités (en particulier les `&` dans les URI).
  - Plus: Les caractères invisibles (`&nbsp;`) DEVRAIENT également l'être, mais pas les autres caractères (p.ex. € ou ⓒ).
- Le code (X)HTML DEVRAIT (DOIT ?) être conforme
- RECOMMANDÉ: bonne formation XML des balises (pas du document)
  - Les éléments devraient avoir une balise de fermeture.
    - TODO: A DISCUTER: y compris pour les éléments vides (`link`, `img`, `br`) ?
  - Noms de balises et d'attributs en minuscules (le XML est sensibles à la casse). (attention toutefois…)
  - Les valeurs d'attribut doivent toujours être entre guillemets (simple ou double). On évite donc les attributs nuls (mais vide: OK).
  - TODO: A DISCUTER: y compris pour les attributs booléens (`required`, `disabled`, `open`) ?
  - Les commentaires ne contiennent pas la séquence `--`.
- Le format HTML5 est RECOMMANDÉ, en syntaxe HTML. Note: Si la page a vocation à être lue informatiquement, on pourra préférer la syntaxe XHTML, mais il est souvent plus commode de disposer les données dans un format directement utile (JSON-LD, RDFa…), d'autant que les règles précédentes sont souvent suffisantes pour assurer l'interprétation du document. Note: la syntaxe XHTML N'EST PAS RECOMMANDÉ pour les concepteurs débutants.
- L'encodage DOIT être précisé. RECOMMANDÉ: `utf-8`.

**Comment by YannisDelmas** [comment]
Sur les attributs booléens: "A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value."
On peut donc probablement interdire les attributs _nuls_ (sans signe `=`) et à les remplacer par des attributs _explicitement vides_.

**Comment by enguerranws** [comment]
Concernant les attributs booléens, pourquoi interdire les attributs seuls ?

`<button type="button" disabled>Je suis un bouton</button>`

Cet exemple me semble valide au regard des specs, de la lisibilité, et le WhatWG précise dans son exemple que les 3 façons d'écrire sont équivalentes : 

```
Here is an example of a checkbox that is checked and disabled. The checked and disabled attributes are the boolean attributes.

<label><input type=checkbox checked name=cheese disabled> Cheese</label>

This could be equivalently written as this:

<label><input type=checkbox checked=checked name=cheese disabled=disabled> Cheese</label>

You can also mix styles; the following is still equivalent:

<label><input type='checkbox' checked name=cheese disabled=""> Cheese</label>

```

Le seul impératif, de ce que je vois, est d'éviter les disabled="true" ou checked="false" : 
`The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.`

**Comment by YannisDelmas** [comment]
Effectivement, du strict point de vue du HTML un attribut nul `abc` et la version vide `abc=""` sont strictement équivalents. En revanche, la 1re écriture est interdite en XML. Mon idée est donc de favoriser la compatibilité avec le XHTML, en particulier pour des bouts de code susceptibles d'être utilisés dans un projet ou un autre.

Point pénible avec les navigateurs (je ne sais pas si c'est toujours le cas): s'il y a le moindre problème de conformité, ils rebasculent en HTML. Or la sémantique est subtilement différente sur certains points. P.ex. les noms de balises sont automatiquement traduits en majuscule (de façon interne) pour le HTML, mais pas pour le XHTML. 😱

**Comment by enguerranws** [comment]
`Effectivement, du strict point de vue du HTML un attribut nul abc et la version vide abc="" sont strictement équivalents. En revanche, la 1re écriture est interdite en XML.`

Ah ok !

`Mon idée est donc de favoriser la compatibilité avec le XHTML, en particulier pour des bouts de code susceptibles d'être utilisés dans un projet ou un autre.`

Je vois. Tu parles de reprendre un bout de code d'un projet de site web à  un autre ? Si c'est le cas, je suis pas sûr que la compatibilité XHTML soit une contrainte qu'il faut vraiment s'imposer : personnellement, ça doit bien faire 7 ou 8 ans que je ne suis pas tombé / que je n'ai pas repris de projet déclaré en XHTML. Mais il y a peut être des cas / des secteurs où ça reste important.

En revanche, d'un autre côté une pratique qui se généralise de plus en plus, ce sont les composants (quels qu'ils soient : WebComponents, React, Vue, etc.), et dans ce contexte, il est très fréquent d'utiliser des attributs / propriétés nuls comme booléen.

**Comment by enguerranws** [comment]
En fait, en reprenant la reco, je me dis qu'on s'embête un peu pour pas grand chose : 
`le code produit est valide` => ça implique qu'on doit le faire valider (et on peut proposer des outils), avec un type de document qui est relatif au document. Je suis pas sûr qu'on ait besoin d'aller plus loin ?

**Comment by YannisDelmas** [comment]
Ça pourrait donc donner cette reformulation. Qu'en pensez-vous?

- L'encodage DOIT être précisé. RECOMMANDÉ: `utf-8` (sans BOM).
- Le balisage DOIT être valide, notamment: 
  - Les éléments DOIVENT être correctement imbriqués.
  - Les caractères spéciaux DOIVENT toujours être correctement échappés par des entités (en particulier les `&` dans les URI).
**Plus** Les caractères invisibles (`&nbsp;`) DEVRAIENT également l'être, mais pas les autres caractères (p.ex. € ou ⓒ).
**Raisons** respect des std ("Using valid HTML is a measurable baseline quality attribute that contributes to learning about technical requirements and constraints, and that ensures proper HTML usage."), sécurité (interprétation univoque).
**Outils** navigateur, vérificateur de l'éditeur de code.
- Format RECOMMANDÉ: HTML5 en syntaxe HTML. Le code DEVRAIT être conforme au format choisi. **Outils** [valideur W3C](https://validator.w3.org/)
- Les éléments DEVRAIENT toujours avoir une balise de fermeture, sauf éventuellement pour les éléments toujours vides (`link`, `img`, `br`).
- Les valeurs d'attribut DOIVENT toujours être entre guillemets (simple ou double), sauf peut-être pour les attributs booléens (p.ex. `required`, `disabled`, `open`).

**Plus** _Si_ le code a vocation à être lu informatiquement ou à être intégré à des pages XHTML (p.ex. un composant réutilisable), il est RECOMMANDÉ d'utiliser une écriture compatible avec le XML, Notamment:
  - Noms de balises et d'attributs en minuscules (le XML est sensibles à la casse). (attention toutefois…)
  - Pas d'attribut nul, même booléen.
  - Les commentaires ne contiennent pas la séquence `--`.
Note: Plutôt que la syntaxe XHTML, il est souvent plus commode d'intégrer les données dans un format directement utile (JSON-LD, RDFa…), d'autant que les règles précédentes sont souvent suffisantes pour assurer l'interprétation du document. La syntaxe XHTML N'EST PAS RECOMMANDÉ pour les concepteurs débutants.

**Comment by YannisDelmas** [comment]
Je viens de relire la checklist Opquast. Certains points pourront être ajoutés en compléments d'information, soit côté "plus" soit côté "justification".

- 125    Internationalisation    Le code source de chaque page indique la langue principale du contenu.
- 225    Structure et code    Le code source de chaque page contient une métadonnée qui définit le jeu de caractères.
- 226    Structure et code    Le codage de caractères utilisé est UTF-8.
- 227    Structure et code    Le contenu de chaque page est organisé selon une structure de titres et sous-titres hiérarchisée. (on en reparle dans une autre recommandation, mais c'est intégré à la conformité HTML 5.2
- 229    Structure et code    Chaque identifiant HTML n'est utilisé qu'une seule fois par page.

**Comment by YannisDelmas** [comment]
@enguerranws Est-ce que cette formulation te convient. J'ai un peu simplifié le bonus de la dernière règle. Il me restera à réécrire les justifications. J'avais déjà rédigé ça une fois, mais j'ai fait une fausse manip' sur Git 😕 (ou un merge s'est mal passé…).

**Comment by enguerranws** [comment]
Oui, ça me convient bien !

**Comment by YannisDelmas** [comment]
OK, super, je recommence l'écriture des justifications, alors.

**Comment by YannisDelmas** [comment]
Voici une première rédaction complète, y compris les justifications. Vous me direz ce que vous en pensez.
